### ISSUE TITLE
Ensure that wallets only use secrets created with the Base58 alphabet

### ISSUE THREAD

**Issue by liamzebedee** [ascribe/transactions#73]
I'm a dumbass and put an apostrophe in mine, and thus cannot get my funds hahaha.

**Comment by liamzebedee** [comment]
For reference, the stack trace looked like:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pycoin-0.70-py3.5.egg/pycoin/encoding.py", line 75, in to_long
    v += lookup_f(c)
  File "/usr/local/lib/python3.5/dist-packages/pycoin-0.70-py3.5.egg/pycoin/encoding.py", line 141, in <lambda>
    v, prefix = to_long(BASE58_BASE, lambda c: BASE58_LOOKUP[c], s.encode("utf8"))
KeyError: 41

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bitcoin-blockchain-notarise/transactions/transactions.py", line 163, in sign_transaction
    BIP32Node.from_text(master_password)
  File "/usr/local/lib/python3.5/dist-packages/pycoin-0.70-py3.5.egg/pycoin/key/Key.py", line 82, in from_text
    data = a2b_hashed_base58(text)
  File "/usr/local/lib/python3.5/dist-packages/pycoin-0.70-py3.5.egg/pycoin/encoding.py", line 161, in a2b_hashed_base58
    data = a2b_base58(s)
  File "/usr/local/lib/python3.5/dist-packages/pycoin-0.70-py3.5.egg/pycoin/encoding.py", line 141, in a2b_base58
    v, prefix = to_long(BASE58_BASE, lambda c: BASE58_LOOKUP[c], s.encode("utf8"))
  File "/usr/local/lib/python3.5/dist-packages/pycoin-0.70-py3.5.egg/pycoin/encoding.py", line 77, in to_long
    raise EncodingError("bad character %s in string %s" % (c, s))
pycoin.encoding.EncodingError: bad character 41 in string
```
